-- LinkStartAI GitHub Projects Archive
-- source: https://github.com/anthropics/skills

insert into public.github_projects (
  slug,
  github_url,
  logo_url,
  name_jsonb,
  slogan_jsonb,
  description_jsonb,
  language,
  license,
  deploy_difficulty,
  tags,
  comparison_jsonb,
  architecture_jsonb,
  deployment_jsonb,
  use_cases_jsonb,
  limitations_jsonb,
  faqs_jsonb,
  seo_title_jsonb,
  seo_description_jsonb,
  is_spotlight,
  spotlight_expires_at,
  view_count,
  sort_order,
  stars,
  tags_jsonb
) values (
  'anthropics-skills',
  'https://github.com/anthropics/skills',
  'https://avatars.githubusercontent.com/u/76263028?v=4',
  '{"en":"Anthropic Skills","zh":"Anthropic 智能体技能库"}'::jsonb,
  '{"en":"Public repository for Agent Skills","zh":"面向智能体的公开技能仓库"}'::jsonb,
  '{"en":"A public, community-forkable repository of reusable agent skills (prompt+tools patterns) maintained by Anthropic, intended to accelerate building reliable AI agents.","zh":"Anthropic 维护的智能体可复用技能库（提示词+工具编排模式），支持社区 Fork，用于加速构建更可靠的 AI Agent。"}'::jsonb,
  'Python',
  'Unknown',
  'easy',
  array['agent-skills','ai-agent','prompt-engineering','skills-library','anthropics'],
  '{"alternatives":[{"name":"obra/superpowers","url":"https://github.com/obra/superpowers","why":"Another open skills collection and patterns for agents."},{"name":"vercel-labs/skills","url":"https://github.com/vercel-labs/skills","why":"Skills collection with a similar concept and structure."}]}'::jsonb,
  '{"overview":"Repository is organized as a catalog of skills; each skill is documented (often in SKILL.md) and can be reused or adapted in agent runtimes.","components":["Skill spec docs","Skill directory structure","Examples/templates"],"integration":"Designed to be consumed by agent frameworks and internal tooling; skills can be referenced as building blocks in workflows."}'::jsonb,
  '{"how_to_deploy":"No deployment required for usage; fork/clone the repo and import/convert skills into your agent runtime or prompt/tool orchestration system.","prerequisites":["Git","An agent runtime/framework that can load or reference skill specs"],"notes":"Best used as a curated source of patterns; adapt to your tool schema and safety policies."}'::jsonb,
  '{"primary":["Bootstrap an internal agent skill library","Standardize prompt/tool patterns across teams","Onboard new engineers with ready-made agent recipes"],"examples":[{"title":"Skill Creator","description":"Use templates/spec to author new skills consistently."}]}'::jsonb,
  '{"items":["Skill format may be framework-specific and require adaptation","Quality varies across contributed skills","Not a turnkey agent runtime by itself"]}'::jsonb,
  '{"items":[{"q":"Is this a runnable framework?","a":"No. It is primarily a skills/spec repository; you integrate the skills into your own agent system."},{"q":"Can I contribute?","a":"Yes—fork and open PRs following repository contribution guidelines."},{"q":"What language is it?","a":"The repo is primarily Python, but skill specs can be language-agnostic."}]}'::jsonb,
  '{"en":"Anthropic Skills (Agent Skills) — reusable AI agent skill library","zh":"Anthropic Skills（Agent Skills）— 可复用 AI 智能体技能库"}'::jsonb,
  '{"en":"Anthropic’s public repository of reusable agent skills and patterns. Great for building and standardizing AI agent prompt+tool workflows.","zh":"Anthropic 开源的智能体技能与模式仓库，用于构建与标准化 AI Agent 的提示词+工具工作流。"}'::jsonb,
  false,
  null,
  0,
  0,
  80821,
  '{"github_topics":["agent-skills"],"signals":{"stars":80821,"forks":8476,"open_issues":360,"watchers":80821},"links":{"repo":"https://github.com/anthropics/skills"}}'::jsonb
)
on conflict (slug) do update set
  github_url = excluded.github_url,
  logo_url = excluded.logo_url,
  name_jsonb = excluded.name_jsonb,
  slogan_jsonb = excluded.slogan_jsonb,
  description_jsonb = excluded.description_jsonb,
  language = excluded.language,
  license = excluded.license,
  deploy_difficulty = excluded.deploy_difficulty,
  tags = excluded.tags,
  comparison_jsonb = excluded.comparison_jsonb,
  architecture_jsonb = excluded.architecture_jsonb,
  deployment_jsonb = excluded.deployment_jsonb,
  use_cases_jsonb = excluded.use_cases_jsonb,
  limitations_jsonb = excluded.limitations_jsonb,
  faqs_jsonb = excluded.faqs_jsonb,
  seo_title_jsonb = excluded.seo_title_jsonb,
  seo_description_jsonb = excluded.seo_description_jsonb,
  is_spotlight = excluded.is_spotlight,
  spotlight_expires_at = excluded.spotlight_expires_at,
  view_count = excluded.view_count,
  sort_order = excluded.sort_order,
  stars = excluded.stars,
  tags_jsonb = excluded.tags_jsonb,
  updated_at = now();
