-- LinkStartAI GitHub Projects Archive
-- source: https://github.com/obra/superpowers

insert into public.github_projects (
  slug,
  github_url,
  logo_url,
  name_jsonb,
  slogan_jsonb,
  description_jsonb,
  language,
  license,
  deploy_difficulty,
  tags,
  comparison_jsonb,
  architecture_jsonb,
  deployment_jsonb,
  use_cases_jsonb,
  limitations_jsonb,
  faqs_jsonb,
  seo_title_jsonb,
  seo_description_jsonb,
  is_spotlight,
  spotlight_expires_at,
  view_count,
  sort_order,
  stars,
  tags_jsonb
) values (
  'obra-superpowers',
  'https://github.com/obra/superpowers',
  'https://avatars.githubusercontent.com/u/45416?v=4',
  '{"en":"Superpowers","zh":"Superpowers 智能体技能框架"}'::jsonb,
  '{"en":"An agentic skills framework & software development methodology that works.","zh":"可落地的智能体技能框架与软件开发方法论。"}'::jsonb,
  '{"en":"Superpowers is an agentic skills framework and development methodology by obra. It focuses on repeatable ‘skills’ that can be composed into agent workflows for real software work.","zh":"Superpowers 是 obra 提供的智能体技能框架与开发方法论，强调可复用技能单元，并可组合成面向真实软件工程任务的 Agent 工作流。"}'::jsonb,
  'Shell',
  'MIT',
  'medium',
  array['ai-agent','agentic-workflows','skills-framework','software-development','methodology','prompt-engineering'],
  '{"alternatives":[{"name":"anthropics/skills","url":"https://github.com/anthropics/skills","why":"Public skills catalog; useful as a complementary reference set."},{"name":"vercel-labs/skills","url":"https://github.com/vercel-labs/skills","why":"Similar ‘skills’ concept and directory-based organization."}]}'::jsonb,
  '{"overview":"A skills-first approach: define, version, and reuse agent skills; then compose them into workflows for software development tasks.","components":["skills/ directory (skill definitions)","methodology (process + conventions)","examples and templates"],"integration":"You typically fork/clone and adapt skills to your own agent runtime, tool schema, and CI practices."}'::jsonb,
  '{"how_to_deploy":"No hosted deployment required. Clone/fork the repository and integrate skills into your agent runtime; optionally wire into CI to validate prompts/specs and enforce conventions.","prerequisites":["Git","Your preferred agent runtime (custom, LLM ops platform, or framework)","Optional: CI (GitHub Actions)"],"notes":"Treat skills like code: review, test (where possible), and version changes."}'::jsonb,
  '{"primary":["Build an internal ‘skills catalog’ for engineering agents","Standardize agent-driven SDLC playbooks","Create repeatable agent workflows for tasks like planning, coding, refactoring, and reviews"],"examples":[{"title":"Brainstorming skill","description":"A reusable skill spec for structured ideation and solution exploration."}]}'::jsonb,
  '{"items":["Not a turnkey agent runtime; requires integration","Skill quality and applicability depends on your tool schema and team practices","Some skills may be prompt/spec-only and need evaluation guardrails"]}'::jsonb,
  '{"items":[{"q":"Is Superpowers a full agent framework?","a":"It is a skills framework and methodology; you still need an agent runtime to execute workflows."},{"q":"What’s the license?","a":"MIT."},{"q":"What language is it?","a":"Primary language is Shell (repo-level), but many skills are framework-agnostic specs."}]}'::jsonb,
  '{"en":"Superpowers — agentic skills framework & software development methodology","zh":"Superpowers — 智能体技能框架与软件开发方法论"}'::jsonb,
  '{"en":"Explore Superpowers (obra): a popular agentic skills framework for composing reusable skills into software-development agent workflows.","zh":"Superpowers（obra）是热门的智能体技能框架，可将可复用技能组合成面向软件工程的 Agent 工作流。"}'::jsonb,
  false,
  null,
  0,
  0,
  67493,
  '{"signals":{"stars":67493,"forks":5173,"open_issues":194,"watchers":67493},"license":{"spdx":"MIT","name":"MIT License"},"links":{"repo":"https://github.com/obra/superpowers"}}'::jsonb
)
on conflict (slug) do update set
  github_url = excluded.github_url,
  logo_url = excluded.logo_url,
  name_jsonb = excluded.name_jsonb,
  slogan_jsonb = excluded.slogan_jsonb,
  description_jsonb = excluded.description_jsonb,
  language = excluded.language,
  license = excluded.license,
  deploy_difficulty = excluded.deploy_difficulty,
  tags = excluded.tags,
  comparison_jsonb = excluded.comparison_jsonb,
  architecture_jsonb = excluded.architecture_jsonb,
  deployment_jsonb = excluded.deployment_jsonb,
  use_cases_jsonb = excluded.use_cases_jsonb,
  limitations_jsonb = excluded.limitations_jsonb,
  faqs_jsonb = excluded.faqs_jsonb,
  seo_title_jsonb = excluded.seo_title_jsonb,
  seo_description_jsonb = excluded.seo_description_jsonb,
  is_spotlight = excluded.is_spotlight,
  spotlight_expires_at = excluded.spotlight_expires_at,
  view_count = excluded.view_count,
  sort_order = excluded.sort_order,
  stars = excluded.stars,
  tags_jsonb = excluded.tags_jsonb,
  updated_at = now();
